version: "3.9"

services:
  app:
    build: .
    container_name: qonita_app
    restart: always
    ports:
      - "8086:80"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: qonita_db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: rootpasswordharusnyaunik
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network: